# --------------
# refer from:
# https://github.com/skhu101/GM-NAS/blob/main/once-for-all-GM/train_ofa_net.py
# --------------

NUM_GPUS: 4
SPACE:
  NAME: 'ofa_mbv3'
LOADER:
  DATASET: 'imagenet'
  NUM_CLASSES: 1000
  BATCH_SIZE: 128
  NUM_WORKERS: 4
  USE_VAL: True
SEARCH:
  MULTI_SIZES: [128,160,192,224]
  LOSS_FUN: 'cross_entropy_smooth'
  LABEL_SMOOTH: 0.1
  WEIGHTS: ''
  AUTO_RESUME: True
OFA:
  TASK: 'normal'
  PHASE: 1
  WIDTH_MULTI_LIST: [1.0]
  KS_LIST: [7]
  EXPAND_LIST: [6]
  DEPTH_LIST: [4]
  CHANNEL_DIVISIBLE: 8
  SUBNET_BATCH_SIZE: 1
  KD_RATIO: 0.
  # KD_PATH: "exp/OFA/teacher_model.pyth"
OPTIM:
  MAX_EPOCH: 180
  BASE_LR: 0.325
  MIN_LR: 1.e-3
  WARMUP_EPOCH: 5
  WARMUP_FACTOR: 1.
  LR_POLICY: 'cos'
  MOMENTUM: 0.9
  WEIGHT_DECAY: 3.e-5
  NESTEROV: True
TEST:
  BATCH_SIZE: 256
  IM_SIZE: 224

