SPACE:
  NAME: 'nasbenchmacro'
LOADER:
  DATASET: 'cifar10'
  NUM_CLASSES: 10
  BATCH_SIZE: 64
OPTIM:
#   BASE_LR: 0.1
#   MOMENTUM: 0.9
#   WEIGHT_DECAY: 0.0005
  MAX_EPOCH: 30
# TRAIN:
#   CHANNELS: 16
#   LAYERS: 8
RMINAS:
  LOSS_BETA: 0.8
  RF_WARMUP: 100
  RF_THRESRATE: 0.05
  RF_SUCC: 100
SEARCH:
  IM_SIZE: 32
OUT_DIR: 'exp/rminas'